data:
    name: Andrea

param_names:
- logm200
- logr200

data_names:
- x
- y
- vrf

priors:
  low:
  - 13.9
  - -0.31
  high:
  - 14.8
  - 0.05
  
val:
  sample_at:
  - 0.5
  - 1
  Nclu: 100
  Nsamp: 100

example:
  sample_at:
  - 0.5
  - 1
  Nclu: 5
  Nsamp: 1000
