# Specify prior
prior:
  module: 'ili.utils'
  class: 'IndependentTruncatedNormal'
  args:
    loc: [13.6993]
    scale: [0.3166]
    low: [13.93]
    high: [14.80]
  
# prior:
#   module: 'ili.utils'
#   class: 'Uniform'
#   args:
#     low: [13.93]
#     high: [14.80]

# proposal:
#   module: 'ili.utils'
#   class: 'IndependentTruncatedNormal'
#   args:
#     loc: [13.6993]
#     scale: [0.3166]
#     low: [13.93]
#     high: [14.80]

# Specify the inference model
model:
  module: 'sbi.inference'
  class: 'SNLE' # Likelihood Estimation
  name: 'gals_nle'
  nets:
    - model: 'maf'  # Masked Autoregressive Flow
      hidden_features: 50 
      num_transforms: 6
    - model: 'mdn'  # Mixture Density Network
      hidden_features: 50 
      num_components: 6

# Specify the neural training hyperparameters   
train_args:
  training_batch_size: 32
  learning_rate: 0.001

device: 'cpu'  # Run on CPU
output_path: './saved_models/gals_nle'  # Where to save the posterior
