# Specify prior
prior:
  # module: 'ili.utils'
  # class: 'IndependentTruncatedNormal'
  # args:
  #   loc: [13.6993]
  #   scale: [0.3166]
  #   low: [13.93]
  #   high: [14.80]
  
prior:
  module: 'ili.utils'
  class: 'IndependentNormal'
  args:
    loc: [13.94]
    scale: [0.373]

# Specify the inference model
model:
  engine: 'NLE' # Likelihood Estimation
  nets:
    - model: 'maf'  # Masked Autoregressive Flow
      hidden_features: 8 
      num_transforms: 3
    - model: 'maf'  # Masked Autoregressive Flow
      hidden_features: 8 
      num_transforms: 3
    # - model: 'maf'  # Masked Autoregressive Flow
    #   hidden_features: 8 
    #   num_transforms: 3
    # - model: 'maf'  # Masked Autoregressive Flow
    #   hidden_features: 8 
    #   num_transforms: 3

# Specify the neural training hyperparameters   
train_args:
  training_batch_size: 256
  learning_rate: 0.001

device: 'cpu'  # Run on CPU
out_dir: './saved_models/gals_nle'  # Where to save the posterior
