# Specify prior

prior:
  module: 'ili.utils'
  class: 'IndependentNormal'
  args:
    loc: [13.94]
    scale: [0.373]

embedding_net:
  module: 'tools.networks'
  class: 'GATNetwork'
  args:
    in_channels: 4
    gcn_channels: [16, 16, 16]
    gcn_heads: [8, 4, 1]
    dense_channels: [16, 8, 8]
    out_channels: 4

# Specify the inference model
model:
  backend: 'lampe'
  engine: 'NPE'  # Posterior Estimation
  nets:
    - model: 'maf' 
      hidden_features: 4
      num_transforms: 2
      x_normalize: False
    - model: 'maf' 
      hidden_features: 4
      num_transforms: 2
      x_normalize: False
    # - model: 'nsf'  # Masked Autoregressive Flow
    #   hidden_features: 8
    #   num_transforms: 4
    #   x_normalize: False

# Specify the neural training hyperparameters
train_args:
  training_batch_size: 16
  learning_rate: 0.00001
  stop_after_epochs: 50

device: 'cpu'  # Run on CPU
out_dir: './saved_models/gnn_npe'  # Where to save the posterior
