# Specify prior

prior:
  module: 'ili.utils'
  class: 'IndependentTruncatedNormal'
  args:
    loc: [13.6993]
    scale: [0.3166]
    low: [13.93]
    high: [14.80]
  
# prior:
#   module: 'ili.utils'
#   class: 'Uniform'
#   args:
#     low: [13.93]
#     high: [14.80]

# proposal:
#   module: 'ili.utils'
#   class: 'IndependentTruncatedNormal'
#   args:
#     loc: [13.6993]
#     scale: [0.3166]
#     low: [13.93]
#     high: [14.80]

# embedding_net:
#   module: 'ili.embedding'
#   class: 'FCN'
#   args:
#     n_data: 19
#     n_hidden: [64, 64]
#     act_fn: "SiLU"

# Specify the inference model
model:
  module: 'sbi.inference'
  class: 'SNLE'  # Posterior Estimation
  name: 'summ_nle'
  nets:
    - model: 'maf'  # Masked Autoregressive Flow
      hidden_features: 50
      num_transforms: 5
    - model: 'maf'  # Masked Autoregressive Flow
      hidden_features: 50
      num_transforms: 5
    #   signature: "maf"
    # - model: 'nsf'  # Neural Spline Flow
    #   hidden_features: 50
    #   num_transforms: 5 
    #   signature: "nsf"
    # - model: 'made'  # Neural Spline Flow
    #   hidden_features: 50
    #   num_transforms: 5 
    #   signature: "made"
    # - model: 'mdn'  # Mixture Density Network
    #   hidden_features: 50 
    #   num_components: 3

# Specify the neural training hyperparameters
train_args:
  training_batch_size: 32
  learning_rate: 0.0001
  stop_after_epochs: 30

device: 'cpu'  # Run on CPU
output_path: './saved_models/summ_nle'  # Where to save the posterior
