# Specify prior

prior:
  module: 'ili.utils'
  class: 'IndependentNormal'
  args:
    loc: [13.94]
    scale: [0.373]

# Specify the inference model
model:
  engine: 'NLE'  # Posterior Estimation
  nets:
    - model: 'maf'  # Masked Autoregressive Flow
      hidden_features: 8
      num_transforms: 4
    - model: 'maf'  # Masked Autoregressive Flow
      hidden_features: 8
      num_transforms: 4
    - model: 'maf'  # Masked Autoregressive Flow
      hidden_features: 8
      num_transforms: 4
    - model: 'maf'  # Masked Autoregressive Flow
      hidden_features: 8
      num_transforms: 4

# Specify the neural training hyperparameters
train_args:
  training_batch_size: 64
  learning_rate: 0.001
  stop_after_epochs: 50

device: 'cpu'  # Run on CPU
out_dir: './saved_models/summ_nle'  # Where to save the posterior
