posterior_file: 'posterior.pkl'  # Path to posterior model
out_dir: './saved_models/gnn_npe'  # Where to save the metrics
style_path: './style.mcstyle'  # Optional matplotlib style file
labels: ['logM200']  # Names of the parameters

# If True, run validation for all networks as one ensemble posterior
# If False, run validation for each network separately
ensemble_mode: True

metrics:
  # Plot an example posterior for a single input
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'  
    args:
      num_samples: 1200
      sample_method: 'direct'  # Direct sampling (only for SNPE)
  
  # Compute and plot coverage metrics across the test set
  coverages:
    module: 'ili.validation.metrics'
    class: 'PosteriorCoverage'
    args:
      save_samples: True
      num_samples: 1000  # per input
      sample_method: 'direct'
      plot_list: ["coverage", "histogram", "predictions", "tarp", "logprob"]
