posterior_file: 'posterior.pkl'  # Path to posterior model
out_dir: './saved_models/summ_nle'  # Where to save the metrics
style_path: './style.mcstyle'  # Optional matplotlib style file
labels: ['logM200']  # Names of the parameters

# If True, run validation for all networks as one ensemble posterior
# If False, run validation for each network separately
ensemble_mode: True

metrics:
  # Plot an example posterior for a single input
  single_example:
    module: 'ili.validation.metrics'
    class: 'PlotSinglePosterior'  
    args:
      num_samples: 1000
      sample_method: 'slice_np_vectorized'
      sample_params:
        num_chains: 4  # use all available cores
        burn_in: 100
        thin: 5
  
  # Compute and plot coverage metrics across the test set
  coverages:
    module: 'ili.validation.metrics'
    class: 'PosteriorCoverage'
    args:
      save_samples: True
      num_samples: 100  # per input
      sample_method: 'slice_np_vectorized'
      sample_params:
        num_chains: 4  # use all available cores
        burn_in: 20
        thin: 5
      plot_list: ["coverage", "histogram", "predictions", "tarp"]
